### PR TITLE
Johns second branch

### PR DESCRIPTION
**Pull request by Jmckinnon10**
Removed the @ from json file.

### CODE REVIEW

**Comment by ProsperousHeart** [comment]
Hey @Jmckinnon10 - you also have #2734 ... Did you open this because you needed to make a change? If so, you can update the old one ... or please close it and let us know to review this one

**Comment by ProsperousHeart** [comment]
> Hey @Jmckinnon10 - you also have #2734 ... Did you open this because you needed to make a change? If so, you can update the old one ... or please close it and let us know to review this one

This has since been closed

**Comment by Jmckinnon10** [comment]
I closed the old branch. This one is up to date and can be reviewed. Sorry for the inconvenience.

**Review by ProsperousHeart — APPROVED** [review]
Approved!

**Pull request merged**
