### PR TITLE
added profile

### PR DESCRIPTION
**Pull request by ebiperej**
I justed added my profile. pls merge

### CODE REVIEW

**Comment by ebiperej** [comment]
Please merge my profile @dga

**Comment by donmarvex** [comment]
Hello @ebiperej , I have noticed that alot of changes have been made to the `src/assets/persons.json` file.
The contribution guidelines only require you to make additions in the `Submissions` directory.

**Comment by ebiperej** [comment]
Hi @donmarvex . thanks for your response. I'm still learning. I might have made a mistake. Could you please tell me what to do?
I'll be very grateful

**Comment by donmarvex** [comment]
> Hi @donmarvex . thanks for your response. I'm still learning. I might have made a mistake. Could you please tell me what to do? I'll be very grateful

Hello @ebiperej , Could you get a fresh copy of the `persons.json` file from the remote repository and delete the one you've made changes on.
Then commit these changes to this same branch.

**Pull request closed without merging**
