### PR TITLE
feat: add information on myself to the list

### PR DESCRIPTION
**Pull request by maryamrmz**

### CODE REVIEW

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
Please remove the `@` from the filename. Other than that - approved!

**Comment by maryamrmz** [comment]
> Please remove the `@` from the filename. Other than that - approved!

But I checked another files, and all of them has ```@```!

**Comment by ProsperousHeart** [comment]
> > Please remove the `@` from the filename. Other than that - approved!
> 
> But I checked another files, and all of them have `@`!

Not all of them, no. Too many, yes.

**Comment by maryamrmz** [comment]
> > > Please remove the `@` from the filename. Other than that - approved!
> > 
> > 
> > But I checked another files, and all of them have `@`!
> 
> Not all of them, no. Too many, yes. Please update as requested.

You're right!
I fixed that!

**Pull request merged**
