### PR TITLE
Email field added

### PR DESCRIPTION
**Pull request by Ayaan2907**
Changes which are done in this PR connecting issue #1802 
 - [x] Added email button.
- [x]  Checks is_valid or not, if it is blank then don't display.
- [x] inserted email field in existing submissions using replace_all option.
- [x] Updated README.md for upcoming submissions.
- [x]  Tested everything on my own JSON file.

### CODE REVIEW

**Review by kennithnichol — COMMENTED** [review]
It might be more efficient to leave the user data alone, and simply hide the email field in the UI IF the user doesn't have one set.

**Comment by Ayaan2907** [comment]
Yes for hiding the unspecified data I did this. Like mentioned in README.md 
> If you do not want to fill some of the fields, leave them blank (e.g. state: "",).

That will not be displayed if the data is unspecified. But if we don't do changes in existing data where the field itself is unspecified it is displaying `unspecified URL`

## Based on my changes
- Email provided
email provided

- Email not provided
email not provided.

**If I am wrong then a humble request please guide me or just give some hints on how to do that!**

**Comment by kennithnichol** [comment]
Thanks for following up! 

To clarify: I am pointing out that we do not need to commit to altering all of the user records by adding the `"email": ""` field.

**Comment by Ayaan2907** [comment]
I got your point, but if we skip that then it will be like this.
if we skip the change
The email button is displayed and showing `mailto: undefined` .

**Comment by kennithnichol** [comment]
Right, so we need to fix the condition that displays that. Possibly by adding something like `(email === '' || typeof email === 'undefined' )`.

But I'm going to say, it's fine - we'll just update the format of the user data.

**Review by kennithnichol — APPROVED** [review]

**Comment by kennithnichol** [comment]
Thank you for doing the work!

**Comment by Ayaan2907** [comment]
> Right, so we need to fix the condition that displays that. Possibly by adding something like `(email === '' || typeof email === 'undefined' )`.
> 
> But I'm going to say, it's fine - we'll just update the format of the user data.
sorry sorry got it now. This is the perfect fix. Thanks for pointing it. It is just a small change. 
Thanks!!!

**Pull request merged**
