### PR TITLE
Revert "Hi everyone! Add my name in this list"

### PR DESCRIPTION
**Pull request by LeiAlan**
Could add me into group, thanks

### CODE REVIEW

**Comment by LeiAlan** [comment]
Hello, I find it will report ：

remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to LeiAlan.
fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requested URL returned error: 403

Do I need a write access permission for it ?

**Comment by SamirJouni** [comment]
You are trying to push directly to the repo. However, all members of the organization do not possess that level of access. Only an owner can push directly to repos. (Obviously, to make sure people don't delete other people's work and so on...)
Therefore, the members and even the owners alike are supposed to make pull requests to the repos, by first forking it. And then comparing the fork (with the changes) to the original.

Same as this guide shows: https://github.com/zero-to-mastery/start-here-guidelines

**Comment by zea3306** [comment]
Can you please add me to the list. The file is too large I cannot open and edit it.

**Comment by khanshehreen** [comment]
Could you please add me to the list. The file is too large I cannot edit it

**Comment by SamirJouni** [comment]
@khanshehreen It is too large for the github's online editor, but you should be able to edit it locally on your PC.

**Pull request closed without merging**
