### PR TITLE
added my json file in submissions

### PR DESCRIPTION
**Pull request by Bennyno**
I added a .json file in the submissions folder, to be added to the job board. Thank you so much!

### CODE REVIEW

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
Please remove the `.gitpod.yml` from your git cache - otherwise approved

**Comment by Bennyno** [comment]
I removed the gitpod.yml file.

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
please remove the `@` from your filename and ensure your username matches the filename. Otherwise approved.

Also - I believe 1 empty line after your data is best practice, but does not interfere with code.

**Comment by Bennyno** [comment]
I removed the @ from the file name, and added the empty line as best practice. Thank you.

**Review by ProsperousHeart — APPROVED** [review]
Approved!

**Pull request merged**
