### PR TITLE
Contribute

### PR DESCRIPTION
**Pull request by JamesSimel**
Please review my **PR!** Thanks :smile: 

@aneagoie 
@notAnkur

### CODE REVIEW

**Comment by JamesSimel** [comment]
please review thank

**Review by w3bdesign — APPROVED** [review]

**Review by w3bdesign — CHANGES_REQUESTED** [review]
@JamesSimel 

Email has been mispelled

**Comment by JamesSimel** [comment]
Thanks, On it

**Comment by JamesSimel** [comment]
Hello Sir @w3bdesign. Please check it up thanks! :pray:

**Comment by JamesSimel** [comment]
And I was thinking that the job-board website needs the background image!
Can I add? thanks

**Review by w3bdesign — APPROVED** [review]
@JamesSimel 

Looks good now!

**Comment by JamesSimel** [comment]
@w3bdesign 
I really appreciate man!

**Comment by JamesSimel** [comment]
Ztm is the gem

**Pull request closed without merging**
