### PR TITLE
Overall update & redesign

### LINKED ISSUE #91: Improve search logic to include location and deprecated_location
If #90 is accepted,some work will be required to make sure the search feature searches through `deprecated_location` AND through `location`.

Also, the Name radio button should be selected by default on page load.

### PR DESCRIPTION
**Pull request by Ekidoxx**
1. Renamed `robots.js` to `persons.js`
2. Updated `persons.js` syntax to version 2.0
3. Fixed bug of filtering by location, that was occurring after above point
4. Redesigned to more modern look

Before & after:
Before & after preview

---

Closes #91, #92, #96, #104

### CODE REVIEW

**Comment by SamirJouni** [comment]
there are conflicts, please pull before you push and make sure to sync your fork with the original repo. Then try to make another pull request. :)

**Comment by Ekidoxx** [comment]
Everything is compatible with the [latest commit](https://github.com/zero-to-mastery/ZtM-Job-Board/commit/52e242ad81b5c186bef3abc5cf0ed95aec09e9c5), but I have updated it locally.

**Comment by SamirJouni** [comment]
I suggest you take a look at this: https://help.github.com/articles/syncing-a-fork/
There are still conflicts in robot.js
Can't merge until they are resolved...

**Comment by Ekidoxx** [comment]
#110

**Pull request closed without merging**
