### PR TITLE
updating to show all developers

### PR DESCRIPTION
**Pull request by gseals**
@MattCSmith I've removed the quotes from the keys of the developer info in an effort to render all of the developers whose info exists in the persons.js file. would you check this out? I'm excited to see my name on the website and I'm looking for jobs so every little bit helps!

### CODE REVIEW

**Comment by MattCSmith** [comment]
Travis still appears to be having a hard time. I will pull down the repo and take a look

**Comment by gseals** [comment]
@MattCSmith thanks! I'm still not showing up on the website and the number of developers at the top doesn't change (it's been at 817 since I first looked at it)

**Comment by MattCSmith** [comment]
Hey @gseals 
Yeah it appeared that Travis was having some issues building the website. 
However check out https://alumni-board.netlify.app/

**Comment by gseals** [comment]
@MattCSmith duuuuuuuuuuuuuuude. that looks great! when does the map feature update?

**Pull request merged**
