### PR TITLE
added myself to submissions

### PR DESCRIPTION
**Pull request by BTBenton10**

### CODE REVIEW

**Comment by BTBenton10** [comment]
says checks were not successful but not sure why. hard for me to understand by just looking at the test. thanks. let me know if i need to fix anything.

**Comment by ProsperousHeart** [comment]
> says checks were not successful but not sure why. hard for me to understand by just looking at the test. thanks. let me know if i need to fix anything.

The file is empty - you can see this at the top of the screen when reviewing the [files changed](https://github.com/zero-to-mastery/ZtM-Job-Board/pull/2726/files) section.

Also - please remove the @ before your username in the JSON file name.

**Comment by BTBenton10** [comment]
sorry i must have forgotten to save. that should  be good now. and i removed the @ as requested thank you!

**Review by ProsperousHeart — APPROVED** [review]
Approved!

**Pull request merged**
