### PR TITLE
Adding me in job board

### PR DESCRIPTION
**Pull request by KalyanKanuri**
add me in in the job board @aneagoie

### CODE REVIEW

**Comment by KalyanKanuri** [comment]
closed without merging

**Comment by ProsperousHeart** [comment]
You closed then re-opened this. You are changing a file that's not yours and then trying to hide it in .gitignore file

Perhaps you should close this and open a new one? If not, please remove the file that is not yours and the line in gitignore

**Comment by KalyanKanuri** [comment]
Hi @ProsperousHeart, Thank you for your suggestion however I didn't add any unknown file could you please let me know which is that file or the line number in .gitignore file?

**Comment by ProsperousHeart** [comment]
> Hi @ProsperousHeart, Thank you for your suggestion however I didn't add any unknown file could you please let me know which is that file or the line number in .gitignore file?

You can see the differences in your PR [files changed](https://github.com/zero-to-mastery/ZtM-Job-Board/pull/2712/files) section (check at top of this page)

image

**Pull request closed without merging**
