### PR TITLE
dark mode added

### PR DESCRIPTION
**Pull request by venkatsai2027**
Hello guys, I added dark mode based on the issue present in the issues tab. It is working fine. Please accept. This is my first open source, excited !!

### CODE REVIEW

**Comment by venkatsai2027** [comment]
@aneagoie @dga please consider this, request issue no #3295 , my pr number #3300

**Comment by l-white** [comment]
@venkatsai2027 Please create a new branch, do your work, and then re-submit. In order to work with your pull request, we'll need you to create a new branch, not work off the master branch. Hopefully this makes sense -- Andrei outlines the process in the Complete Web Developer course. You can also ask for help in the community. In the meantime, I am going to close this PR so you can try again, but dark mode is a good idea, so please create a new branch and re-submit your changes.

**Comment by venkatsai2027** [comment]
@l-white thank you so much mam, I learned some new things because of this. This is my first time working on open source, please don't mind. I understood the problem, I will open new PR. Thank you so much.

**Comment by l-white** [comment]
@venkatsai2027 No worries at all. We are here to support your learning. We are busy getting ready for Hacktoberfest but will try to take a look at your PR in a few days. Thank you for your interest in adding a feature to the app.

**Comment by venkatsai2027** [comment]
Thank you so much mam!!!

**Pull request closed without merging**
