### PR TITLE
switch to hooks, cursor pointer to logo and remove onkeypress

### PR DESCRIPTION
**Pull request by phaniteja1**
1. Switched to react hooks
2. Add pointer class to logo for cursor:pointer
3. Remove onKeyPress for search bar as onChange was doing the job

### CODE REVIEW

**Comment by SamirJouni** [comment]
Hello, 
I'm curious... is there any benefit of going with this functional components + react hooks approach instead of class components ?

**Comment by phaniteja1** [comment]
> Hello,
> I'm curious... is there any benefit of going with this functional components + react hooks approach instead of class components ? @SamirJouni 

Please refer to this section: [React Hooks Motivation](https://reactjs.org/docs/hooks-intro.html#motivation)

Also you can write some really powerful and reusable custom hooks. Here are some examples:
[Use Hooks](https://usehooks.com/)

**Comment by SamirJouni** [comment]
That was very informative, thank you. 
React hooks seem to be very interesting. I've been putting them off because I thought they were just another gimmick, but they seem to be very useful. I guess I might use them myself in a future project! :)

**Comment by phaniteja1** [comment]
@SamirJouni  Is this a real job board or just a playground for beginner programmers? Thanks.

**Pull request merged**
