### PR TITLE
changed the nav bar styling and the filter in responsive mode

### PR DESCRIPTION
**Pull request by wassimbj**
i changed the filter in responsive mode and also the nav bar, hope you liked it :)

### CODE REVIEW

**Comment by wassimbj** [comment]
Hey samir can you tell me what was the issue ? did i forgot something ?

**Comment by wassimbj** [comment]
Thanks for removing that samir i forgot about it :)

**Comment by SamirJouni** [comment]
No problem ! Anytime. :)
Just took a look at the changes. Good job. 💯

**Comment by wassimbj** [comment]
Thanks samir :)

**Pull request merged**
