### PR TITLE
Added my profile

### PR DESCRIPTION
**Pull request by Sayed-Afnan-Khazi**
Hello, I've added my profile according to the template. Please let me know if you need any changes. Thanks!

### CODE REVIEW

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
This is an empty file - please provide the info from the README.md

**Comment by Sayed-Afnan-Khazi** [comment]
Sorry, I forgot to save before committing and pushing. I have pushed my card to the same branch again. Hope this works!

**Review by ProsperousHeart — APPROVED** [review]
Approved!

**Comment by Sayed-Afnan-Khazi** [comment]
Thank you, @ProsperousHeart!

**Pull request merged**
