### PR TITLE
add photo + profile info

### PR DESCRIPTION
**Pull request by mikelammy**
please accept my pull request so that my name and photo can be a part of the jobBoard website.  @aneagoie @MattCSmith @kennithnichol

### CODE REVIEW

**Comment by mikelammy** [comment]
> donmarvex

@donmarvex  thank you for the reply Don!  I wanted a photo because I want my picture to be on the website: https://alumni-board.netlify.app/

But I am having difficulty with it.  I included my photo in a png file named: mike_photo.png inside the ZtM-Job-Board directory.  Inside Submissions, I followed the ReadMe and added https://github.com/mike-photo.png in the img section of the 1-mikelammy.json file inside Submission.  

{
  "name": "Mike Lam",
  "img": "https://github.com/mike-photo.png",
  "email": "mdlam88@gmail.com",
  "links": {
    "website": "https://mikelammy.github.io/landingPage/",
    "linkedin": "https://www.linkedin.com/in/mike-t-lam",
    "github": "https://github.com/mikelammy"
  },
  "jobTitle": "Software Developer",
  "location": {
    "city": "San Jose",
    "state": "California",
    "country": "United States"
  }
}


HELP:  I am totally confused on how to add my photo so that it can appear on the website https://alumni-board.netlify.app/.

can you please help me with this?

**Comment by mikelammy** [comment]
Screen Shot 2022-06-15 at 4 12 51 PM

here is a screen of my photo named mike_photo.png inside the ZtM-Job-Board directory.

however, I do not know how to make my photo appear inside the website: https://alumni-board.netlify.app/

please advise,

Mike

**Comment by mikelammy** [comment]
@aneagoie @donmarvex @MattCSmith @kennithnichol 
can you help show me how to add a valid link to my profile link.  I read the README section on how to do it, but I still cannot add photo.  the above details what I have done

**Comment by kennithnichol** [comment]
@mikelammy you need to **add a profile photo to your GitHub account**. The URL http://github.com/<username>.png actually does generate your profile photo as a valid image. Example:  https://github.com/kennithnichol.png

**Comment by mikelammy** [comment]
@kennithnichol @donmarvex 
I listened to your advice, Kenni.

1) I uploaded the photo onto my github account.
2) I entered https://github.com/mikelammy.png onto browser and got https://avatars.githubusercontent.com/u/78281264?v=4 when I pressed entered.
3) I copied this URL: https://avatars.githubusercontent.com/u/78281264?v=4 into the .json file in the Submission directory.  More specifically I pasted it into the IMG area for image.
4) On terminal, I did the following steps:
     a) on smaller branch named TEST :   git add .
     b)                                                         git commit -m "add url into jsonFile and deleted png photo in Submission Directory"
     c)                                                         git push
5) awaiting approval for Pull Request if everything is done correctly

**Pull request merged**
