### PR TITLE
Mohtady on board

### PR DESCRIPTION
**Pull request by MohtadyDeveloper**
Adding My Avatar

### CODE REVIEW

**Comment by MohtadyDeveloper** [comment]
When I can see my self here https://alumni-board.netlify.app/

**Comment by l-white** [comment]
@MohtadyDeveloper Could you replace the website with "" if you don't have one? I see the placeholder text in the commit.

**Comment by MohtadyDeveloper** [comment]
I replaced the website with ""

**Comment by MohtadyDeveloper** [comment]
{
    "name": "Mohtady Ekmail",
    "img": "https://avatars.githubusercontent.com/u/128006116?v=4",
    "email": "Mohtady.developer@gmail.com",
    "links": {
      "website": "",
      "linkedin": "https://www.linkedin.com/in/mohtady-ekmail-35ab08b",
      "github": "https://github.com/MohtadyDeveloper"
    },
    "jobTitle": "Full Stack Developer",
    "location": {
      "city": "Roseville",
      "state": "Sacramento, California",
      "country": "USA"
    }
  }

**Comment by MohtadyDeveloper** [comment]
correct?

**Comment by l-white** [comment]
@MohtadyDeveloper This is correct but you need to push the change to the code as you did for the other changes. Once you commit that change we can merge your pull request

**Pull request merged**
