### PR TITLE
Arooj

### PR DESCRIPTION
**Pull request by arooj-12**

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Please only add _one_ file with your name/submission @arooj-12

**Comment by sophiabrandt** [comment]
@arooj-12 are you still interested in this PR?

**Comment by arooj-12** [comment]
Yes I am. I have only pushed one file.

**Comment by sophiabrandt** [comment]
@arooj-12 As you can see in the files tab on this page there are changes to 3 files. Please fix that, otherwise we cannot accept your pull request.

**Comment by majidshakeelshawl** [comment]
Hi @arooj-12, I think you are getting confused with the requested changes, actually the reviewer is asking you to do the following changes
- UNDO the changes in the `0ifechukwu-daniel.json` as the file belongs to someone else.
- DELETE the other `1-arooj.json` file as it doesn't match with your github username.

_NOTE:_ Only keep one file i.e `arooj-12.json`

**Comment by sophiabrandt** [comment]
@arooj-12 Hey, just letting you know that I'm going to close your PR in a few days.
If you do not want to go through the work of making the requested changes, it might be easier to start fresh with a new pull request.

**Pull request closed without merging**
