### PR TITLE
Add CONTRIBUTORS.md, persons.js

### PR DESCRIPTION
**Pull request by SaboyaDev**
Added my profile information to the persons.js file as well as my GitHub username to the CONTRIBUTORS.md file

### CODE REVIEW

**Comment by MattCSmith** [comment]
Hey @SaboyaDev 
Unfortunately there is a conflict on this PR I am unable to resolve on my end. 
If you can address the conflict so we can merge the PR that would be fantastic.

**Comment by SaboyaDev** [comment]
> Hey @SaboyaDev
> Unfortunately there is a conflict on this PR I am unable to resolve on my end.
> If you can address the conflict so we can merge the PR that would be fantastic.

IDK what happened, I did another pull request and two other people's info info was in place of mine so I caused a conflict. I did a pull request to from the upstream so it said I was in sync prior to requesting the pull request.

**Comment by MattCSmith** [comment]
@SaboyaDev Perfect thank you. I think what it might have been, is there were a couple of other PRs waiting to be merged before yours. So when those were merged yours then conflicted. 
Unfortunately its just one of the things with opensource

**Comment by SaboyaDev** [comment]
> @SaboyaDev Perfect thank you. I think what it might have been, is there were a couple of other PRs waiting to be merged before yours. So when those were merged yours then conflicted.
> Unfortunately its just one of the things with opensource

thank you so much. This was such a great experience with pull request and merges I haven't really done this and I'm glad it worked out. Looking forward to working on other open source projects.

**Pull request merged**
