### PR TITLE
added username

### PR DESCRIPTION
**Pull request by satoshimasterbilly**
Please add my username to the list.

### CODE REVIEW

**Review by vikasganiga05 — APPROVED** [review]
LGTM :+1:

**Review by sophiabrandt — CHANGES_REQUESTED** [review]
Please remove `.DS_Store`.

**Review by vikasganiga05 — CHANGES_REQUESTED** [review]
Hey @satoshimasterbilly, As @sophiabrandt said remove Submodule & `.DS_Store`.

**Comment by sophiabrandt** [comment]
Please remove all other files and folders except the `.json`.

**Pull request closed without merging**
