### PR TITLE
Added my JSON file to Submissions

### PR DESCRIPTION
**Pull request by gentcod**

### CODE REVIEW

**Comment by sophiabrandt** [comment]
Please revert your changes to `src/assets/persons.json`.

**Comment by gentcod** [comment]
> Please revert your changes to `src/assets/persons.json`.

The changes were made automatically after I initialized 'npm start'.. Should I revert it regardless??

**Comment by sophiabrandt** [comment]
> > Please revert your changes to `src/assets/persons.json`.
> 
> The changes were made automatically after I initialized 'npm start'.. Should I revert it regardless??

That's unfortunate.

But yes, please only add your submission and delete all other changes.

**Comment by gentcod** [comment]
> > > Please revert your changes to `src/assets/persons.json`.
> > 
> > 
> > The changes were made automatically after I initialized 'npm start'.. Should I revert it regardless??
> 
> That's unfortunate.
> 
> But yes, please only add your submission and delete all other changes.

I have reverted the change to` src/assets/persons.json` and made the proper corrections.

**Pull request merged**
