### PR TITLE
added my name

### PR DESCRIPTION
**Pull request by HassanNewDev**
{
    "name": "Hassan Abdi",
    "img": "https://avatars.githubusercontent.com/u/110099736?s=96&v=4",
    "email": "mrhassanabdi1@gmail.com",
    "links": {
    "website": "https://myportfolio-hassandev.netlify.app/#",
    "linkedin": "",
    "github": "https://github.com/hassannewdev"
    },
    "jobTitle": "Frontend Web Developer ",
    "location": {
    "city": "London",
    "state": "",
    "country": "United Kingdom"
    }
    }

### CODE REVIEW

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
Please udpate the filename to match your GitHub username - including casing

**Comment by HassanNewDev** [comment]
> Please update the filename to match your GitHub username - including casing

i updated my filename to match my GitHub username.

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
Please ensure it also includes the proper casing for your username in your filename

**Comment by HassanNewDev** [comment]
i already done that

**Comment by ProsperousHeart** [comment]
> i already done that

image

**Comment by HassanNewDev** [comment]
the recent one is correct "chaned filename casing"

**Review by ProsperousHeart — APPROVED** [review]
While approved, please be aware of spacing. Your last `}` is not properly aligned. While this specific instance won't be an issue, it can be a problem in other code.

**Pull request merged**
