### PR TITLE
Revert "Hi everyone! Add my name in this list"

### PR DESCRIPTION
**Pull request by gongendir**
Hi, Im getting "permission" error.

### CODE REVIEW

**Comment by SamirJouni** [comment]
There appears to be a conflict, please pull before you push and make sure you sync your fork: https://help.github.com/articles/syncing-a-fork/

Good Luck!

**Comment by gongendir** [comment]
Hello there, I pulled and tried push to origin master but Im getting
permission denied, Do I need to SSH key ?

Samir Jouni <notifications@github.com>, 5 Oca 2019 Cmt, 02:37 tarihinde
şunu yazdı:

**Comment by SamirJouni** [comment]
I see...
You cannot push to the original repository, i.e. the zero-to-mastery organization's repository. You can only push to your fork. Make sure that your local files are linked to your fork, not the original repo.

**Comment by gongendir** [comment]
Thank you Samir,

I solved problem just like you said.

Regards

Samir Jouni <notifications@github.com>, 6 Oca 2019 Paz, 02:54 tarihinde
şunu yazdı:

**Comment by SamirJouni** [comment]
That's good to hear, but your fork is still behind. There still are conflicts. 
Good Luck ! :)

**Comment by khanshehreen** [comment]
Can you please add me to the list

**Pull request closed without merging**
