### PR TITLE
Added my name to ZTM Board list

### PR DESCRIPTION
**Pull request by NirajBhavnani**

### CODE REVIEW

**Comment by NirajBhavnani** [comment]
Added my info the job board. @ProsperousHeart 
@zero-to-mastery/gitgang @dga @alejandroiglesias @Cyph3r @tgmarinho @aneagoie

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
Please remove the `@` from the filename - other than that, approved!

**Comment by NirajBhavnani** [comment]
> Please remove the `@` from the filename - other than that, approved!

Done the changes @ProsperousHeart. Please approve the same! 😄

**Review by ProsperousHeart — APPROVED** [review]
Approved!

**Pull request merged**
