### PR TITLE
Create @masanbasa3k.json

### PR DESCRIPTION
**Pull request by masanbasa3k**
I created my json file.

### CODE REVIEW

**Comment by masanbasa3k** [comment]
Hello, @ProsperousHeart, could you please add my name to the list? Thank you.

**Review by ProsperousHeart — CHANGES_REQUESTED** [review]
1. please remove the `@` from filename
2. please ensure your country is a current country, or else it will not show on the map

**Comment by masanbasa3k** [comment]
@ProsperousHeart Thank you for helping to me. I did the things you told me.

**Review by ProsperousHeart — APPROVED** [review]
Approved!

**Pull request merged**
