### PR TITLE
Adding my file into submissions folder

### PR DESCRIPTION
**Pull request by noufanelachola**
I've added noufanelachola.json, which contains my details, to the Submissions folder.

### CODE REVIEW

**Comment by noufanelachola** [comment]
@aneagoie

**Comment by noufanelachola** [comment]
It's okay ,right?

**Comment by noufanelachola** [comment]
@daniel-farlow

**Comment by l-white** [comment]
@noufanelachola Yes, all is well with your pull request. Nice job!

**Comment by noufanelachola** [comment]
@l-white Thank you

**Pull request merged**
