### PR TITLE
adding cedricliu to the list

### PR DESCRIPTION
**Pull request by cedricliu**
Should have created a branch... anyways, please adds me to the board list, thank you!

### CODE REVIEW

**Comment by SamirJouni** [comment]
Your fork seems to be out of date, I suggest you try syncing it: https://help.github.com/articles/syncing-a-fork/
And if that fails, then maybe try to delete the fork and start over again. 

Good Luck ! :)

**Comment by cedricliu** [comment]
So I tried the process again, and it appears this problem: 
remote: Permission to zero-to-mastery/ZtM-Job-Board.git denied to cedricliu.
fatal: unable to access 'https://github.com/zero-to-mastery/ZtM-Job-Board.git/': The requested URL returned error: 403

**Comment by SamirJouni** [comment]
Error 403 means permission denied and that's perfectly normal when you try to directly push to the repo of the organization. Since you're a member of the organization and not an owner, you don't have the authorization to push directly, but only to make pull requests. 

The Solution: 
Push to your fork, instead of pushing to the ztm job board. You need to set the upstream to the fork repo, while origin to the original repo. 
Also, persons.js is not longer in the src/ directory. It is in the src/components/ directory.

Try to update your fork by following the guide in the link that I showed you. Or better yet, delete the fork and then fork it again, make sure to copy your entry into persons.js to notepad or any other text editor before you delete the fork, so you don't have to do it all over again. Then modify persons.js in the new fork by pasting your details into persons.js, remember to paste them before the closing array square brackets "];". And then make a pull request from the fork again.

The second solution is better in my opinion, because it's less tedious. The first solution however will teach you how github actually works, a lot better.

**Comment by cedricliu** [comment]
Thank you for the information! I cloned on the main URL, should have used my own fork. :) It's all working now.

**Pull request closed without merging**
