### PR TITLE
adding myself to the json

### PR DESCRIPTION
**Pull request by gseals**
- please add me to the list, @royranger @aneagoie

### CODE REVIEW

**Comment by MattCSmith** [comment]
@gseals There is a merge conflict I am unable to rectify on my end, please resolve this conflict and repush. 🙂

**Comment by gseals** [comment]
@MattCSmith I think I've done it. Please let me know if there are other issues I need to resolve.

**Comment by MattCSmith** [comment]
Perfect thanks @gseals  👍

**Comment by gseals** [comment]
thanks, @MattCSmith

**Comment by gseals** [comment]
@MattCSmith do you know how long it takes for the website to update with my information?

**Comment by MattCSmith** [comment]
@gseals It appears a rogue persons.js was created
The website is upto date, but it only reads data from `/src/assets/persons.js`

**Comment by gseals** [comment]
@MattCSmith oh, no! it appears I'm in the non-asset path persons.json . I'll update and repush myself into the correct file.

**Pull request merged**
