### PR TITLE
Added myself to the project

### PR DESCRIPTION
**Pull request by Baisch91**

### CODE REVIEW

**Comment by MattCSmith** [comment]
@Baisch91 There is a merge conflict present on this PR, that I am unable to resolve. Please resolve and repush 🙂

**Comment by Baisch91** [comment]
@MattCSmith I believe I've resolved the conflict. Please check to make sure. Thank you.

**Comment by sophiabrandt** [comment]
@Baisch91 Unfortunately, it still doesn't work. Can you please check again and see if you can resolve the merge conflict?

**Comment by StefanSelfTaught** [comment]
Lol @Shubhamai why did you merge this? There are 400 deleted lines of code with some persons ..

**Comment by Shubhamai** [comment]
Ah, sorry @StefanSelfTaught 😟, learning from mistakes, will be more focused while merging anything from now.

**Comment by Baisch91** [comment]
Oh my... I don't know how that happen, but I do apologize if it was from my end. Is there anything I should do on my end? Should I create a new fork, sync it and try again?

**Comment by StefanSelfTaught** [comment]
@Shubhamai It's ok, I resolve it easily by reverting the pull request 😄

**Comment by StefanSelfTaught** [comment]
@Baisch91 Don't worry 😄, you can add your profile again through a pull request.

**Pull request merged**
